spring:
  application:
    name: yandex-sprint-4-blog
    content-path: ${CONTENT_PATH}
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: test
    password: test
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql