SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE comment;
TRUNCATE TABLE post;

ALTER TABLE comment ALTER COLUMN id RESTART WITH 1;
ALTER TABLE post ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;
-- delete from post where true;